### ISSUE TITLE
regtest: generating 102 blocks for coinbase maturity with bitcoin core will then make ord say "error: reorg detected at or before 101"

### ISSUE THREAD

**Issue by tiero** [casey/ord#1638]
1. I have successfully created a ord wallet against by Bitcoin Core in regtest
2. I have  generated 101 blocks for coinbase maturity, directly to the ord wallet
3. I make my inscription, where I get commit & reveal txids

Now any command ie. "ord wallet inscriptions" will return ""error: reorg detected at or before 101"

I replicate this with redb deleted and bitcoin datadir cleaned up multiple times, no ways to go beyond block 102

**Comment by dajuguan** [comment]
Could you put you related bitcoin.conf, bitcoind and ord commands please?
I just cannot  successfuly run the `ord wallet create` command, it says:
`error: failed to connect to Bitcoin Core RPC at 127.0.0.1:18443/wallet/ord`
Thanks!

**Comment by tiero** [comment]
I run Bitcoin Core in a docker container like below and reference the cookie file from the mounted volume.

```yaml
version: "3.9"
services:
  bitcoin:
    image: lncm/bitcoind:v24.0.1
    container_name: bitcoind
    # wildcard user 0:0 to avoid permission problems
    user: 0:0
    restart: on-failure
    stop_grace_period: 30s
    command: 
      - --regtest 
      - --port=18444
      - --txindex=1
      - --server=1
      - --rpcauth=bitcoin:cd2fee0b399aa5ac099ef1b79a5e0bed$$50af3f323dabbf5c460f8b5e99af486a396c3157744ab4b766b620db9962223b
      - --rpcport=18443 
      - --rpcbind=0.0.0.0
      - --rpcallowip=0.0.0.0/0
    ports:
      - "18444:18444"
      - "18443:18443"
    volumes:
      - ${PWD}/volumes/bitcoin:/root/.bitcoin
```
